### ISSUE TITLE
Double tap on iphone with accordion show-more

### ISSUE THREAD

**Issue by pvansteenoven** [briangraves/ResponsiveEmailPatterns#2]
We found a bug with iphone 4 and 5 that to open up an accordion you need to press twice. Could you look into it please?

Thank you

Paul

**Comment by briangraves** [comment]
iOS appears to treat the first tap as a hover state. So first tap triggers :hover and second tap triggers :active. One possible solution would be to change the :active trigger in the css to :hover. This solution appears to work across iOS and Android. It does however mean the accordion will trigger on mouseover for non-touch devices (desktop). I'll look to see if I can work out a good solution.
